version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: auth_app_service_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_app_service_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
